version: '3.8'
services:
  api:
    image: tuvia-api-prod
    build:
      context: .
      dockerfile: Dockerfile.production
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/tuvia

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
